# Generated by Django 3.1 on 2020-09-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depandemic', '0002_auto_20200908_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorized_contents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
